// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: bank.proto

package v1_1

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// BankService defines service.
type BankService interface {
	// CreateUser CreateUser 创建用户
	// @alias="/user/create"
	CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserRsp, error)
	// Login Login 用户登陆
	// @alias="/user/login"
	Login(ctx context.Context, req *LoginReq) (*LoginRsp, error)
	// CreateAccount CreateAccount 创建账户
	// @alias="/account/create"
	CreateAccount(ctx context.Context, req *CreateAccountReq) (*CreateAccountRsp, error)
	// GetAccount GetAccount 查询账户
	// @alias="/account"
	GetAccount(ctx context.Context, req *GetAccountReq) (*GetAccountRsp, error)
	// ListAccounts ListAccounts 账户列表查询
	// @alias="/account/list"
	ListAccounts(ctx context.Context, req *ListAccountsReq) (*ListAccountsRsp, error)
	// Transfer Transfer 转账
	// @alias="/transfer"
	Transfer(ctx context.Context, req *TransferReq) (*TransferRsp, error)
}

func BankService_CreateUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateUserReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BankService).CreateUser(ctx, reqbody.(*CreateUserReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BankService_Login_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &LoginReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BankService).Login(ctx, reqbody.(*LoginReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BankService_CreateAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BankService).CreateAccount(ctx, reqbody.(*CreateAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BankService_GetAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BankService).GetAccount(ctx, reqbody.(*GetAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BankService_ListAccounts_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListAccountsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BankService).ListAccounts(ctx, reqbody.(*ListAccountsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BankService_Transfer_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &TransferReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BankService).Transfer(ctx, reqbody.(*TransferReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// BankServer_ServiceDesc descriptor for server.RegisterService.
var BankServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "bank.v1_1.Bank",
	HandlerType: ((*BankService)(nil)),
	Methods: []server.Method{
		{
			Name: "/user/create",
			Func: BankService_CreateUser_Handler,
		},
		{
			Name: "/user/login",
			Func: BankService_Login_Handler,
		},
		{
			Name: "/account/create",
			Func: BankService_CreateAccount_Handler,
		},
		{
			Name: "/account",
			Func: BankService_GetAccount_Handler,
		},
		{
			Name: "/account/list",
			Func: BankService_ListAccounts_Handler,
		},
		{
			Name: "/transfer",
			Func: BankService_Transfer_Handler,
		},
		{
			Name: "/bank.v1_1.Bank/CreateUser",
			Func: BankService_CreateUser_Handler,
		},
		{
			Name: "/bank.v1_1.Bank/Login",
			Func: BankService_Login_Handler,
		},
		{
			Name: "/bank.v1_1.Bank/CreateAccount",
			Func: BankService_CreateAccount_Handler,
		},
		{
			Name: "/bank.v1_1.Bank/GetAccount",
			Func: BankService_GetAccount_Handler,
		},
		{
			Name: "/bank.v1_1.Bank/ListAccounts",
			Func: BankService_ListAccounts_Handler,
		},
		{
			Name: "/bank.v1_1.Bank/Transfer",
			Func: BankService_Transfer_Handler,
		},
	},
}

// RegisterBankService registers service.
func RegisterBankService(s server.Service, svr BankService) {
	if err := s.Register(&BankServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Bank register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedBank struct{}

// CreateUser CreateUser 创建用户
// @alias="/user/create"
func (s *UnimplementedBank) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserRsp, error) {
	return nil, errors.New("rpc CreateUser of service Bank is not implemented")
}

// Login Login 用户登陆
// @alias="/user/login"
func (s *UnimplementedBank) Login(ctx context.Context, req *LoginReq) (*LoginRsp, error) {
	return nil, errors.New("rpc Login of service Bank is not implemented")
}

// CreateAccount CreateAccount 创建账户
// @alias="/account/create"
func (s *UnimplementedBank) CreateAccount(ctx context.Context, req *CreateAccountReq) (*CreateAccountRsp, error) {
	return nil, errors.New("rpc CreateAccount of service Bank is not implemented")
}

// GetAccount GetAccount 查询账户
// @alias="/account"
func (s *UnimplementedBank) GetAccount(ctx context.Context, req *GetAccountReq) (*GetAccountRsp, error) {
	return nil, errors.New("rpc GetAccount of service Bank is not implemented")
}

// ListAccounts ListAccounts 账户列表查询
// @alias="/account/list"
func (s *UnimplementedBank) ListAccounts(ctx context.Context, req *ListAccountsReq) (*ListAccountsRsp, error) {
	return nil, errors.New("rpc ListAccounts of service Bank is not implemented")
}

// Transfer Transfer 转账
// @alias="/transfer"
func (s *UnimplementedBank) Transfer(ctx context.Context, req *TransferReq) (*TransferRsp, error) {
	return nil, errors.New("rpc Transfer of service Bank is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// BankClientProxy defines service client proxy
type BankClientProxy interface {
	// CreateUser CreateUser 创建用户
	// @alias="/user/create"
	CreateUser(ctx context.Context, req *CreateUserReq, opts ...client.Option) (rsp *CreateUserRsp, err error)
	// Login Login 用户登陆
	// @alias="/user/login"
	Login(ctx context.Context, req *LoginReq, opts ...client.Option) (rsp *LoginRsp, err error)
	// CreateAccount CreateAccount 创建账户
	// @alias="/account/create"
	CreateAccount(ctx context.Context, req *CreateAccountReq, opts ...client.Option) (rsp *CreateAccountRsp, err error)
	// GetAccount GetAccount 查询账户
	// @alias="/account"
	GetAccount(ctx context.Context, req *GetAccountReq, opts ...client.Option) (rsp *GetAccountRsp, err error)
	// ListAccounts ListAccounts 账户列表查询
	// @alias="/account/list"
	ListAccounts(ctx context.Context, req *ListAccountsReq, opts ...client.Option) (rsp *ListAccountsRsp, err error)
	// Transfer Transfer 转账
	// @alias="/transfer"
	Transfer(ctx context.Context, req *TransferReq, opts ...client.Option) (rsp *TransferRsp, err error)
}

type BankClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewBankClientProxy = func(opts ...client.Option) BankClientProxy {
	return &BankClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *BankClientProxyImpl) CreateUser(ctx context.Context, req *CreateUserReq, opts ...client.Option) (*CreateUserRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/user/create")
	msg.WithCalleeServiceName(BankServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Bank")
	msg.WithCalleeMethod("CreateUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateUserRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BankClientProxyImpl) Login(ctx context.Context, req *LoginReq, opts ...client.Option) (*LoginRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/user/login")
	msg.WithCalleeServiceName(BankServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Bank")
	msg.WithCalleeMethod("Login")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &LoginRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BankClientProxyImpl) CreateAccount(ctx context.Context, req *CreateAccountReq, opts ...client.Option) (*CreateAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/account/create")
	msg.WithCalleeServiceName(BankServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Bank")
	msg.WithCalleeMethod("CreateAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BankClientProxyImpl) GetAccount(ctx context.Context, req *GetAccountReq, opts ...client.Option) (*GetAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/account")
	msg.WithCalleeServiceName(BankServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Bank")
	msg.WithCalleeMethod("GetAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BankClientProxyImpl) ListAccounts(ctx context.Context, req *ListAccountsReq, opts ...client.Option) (*ListAccountsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/account/list")
	msg.WithCalleeServiceName(BankServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Bank")
	msg.WithCalleeMethod("ListAccounts")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListAccountsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BankClientProxyImpl) Transfer(ctx context.Context, req *TransferReq, opts ...client.Option) (*TransferRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/transfer")
	msg.WithCalleeServiceName(BankServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Bank")
	msg.WithCalleeMethod("Transfer")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &TransferRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
