// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: bank.proto

package v1_1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_bank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateUserReq) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedUser   *User                  `protobuf:"bytes,1,opt,name=created_user,json=createdUser,proto3" json:"created_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRsp) Reset() {
	*x = CreateUserRsp{}
	mi := &file_bank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRsp) ProtoMessage() {}

func (x *CreateUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRsp.ProtoReflect.Descriptor instead.
func (*CreateUserRsp) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRsp) GetCreatedUser() *User {
	if x != nil {
		return x.CreatedUser
	}
	return nil
}

type User struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserName          string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName          string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email             string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PasswordChangedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=password_changed_at,json=passwordChangedAt,proto3" json:"password_changed_at,omitempty"`
	CreateAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_bank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPasswordChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PasswordChangedAt
	}
	return nil
}

func (x *User) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_bank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UserInfo      *User                  `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRsp) Reset() {
	*x = LoginRsp{}
	mi := &file_bank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRsp) ProtoMessage() {}

func (x *LoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRsp.ProtoReflect.Descriptor instead.
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRsp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginRsp) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type CreateAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountReq) Reset() {
	*x = CreateAccountReq{}
	mi := &file_bank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReq) ProtoMessage() {}

func (x *CreateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReq.ProtoReflect.Descriptor instead.
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountReq) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateAccountReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateAccountRsp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CreatedAccount *Account               `protobuf:"bytes,1,opt,name=created_account,json=createdAccount,proto3" json:"created_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRsp) Reset() {
	*x = CreateAccountRsp{}
	mi := &file_bank_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRsp) ProtoMessage() {}

func (x *CreateAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRsp.ProtoReflect.Descriptor instead.
func (*CreateAccountRsp) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountRsp) GetCreatedAccount() *Account {
	if x != nil {
		return x.CreatedAccount
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_bank_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{7}
}

func (x *Account) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Account) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type GetAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountReq) Reset() {
	*x = GetAccountReq{}
	mi := &file_bank_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountReq) ProtoMessage() {}

func (x *GetAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountReq.ProtoReflect.Descriptor instead.
func (*GetAccountReq) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAccountRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRsp) Reset() {
	*x = GetAccountRsp{}
	mi := &file_bank_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRsp) ProtoMessage() {}

func (x *GetAccountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRsp.ProtoReflect.Descriptor instead.
func (*GetAccountRsp) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountRsp) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsReq) Reset() {
	*x = ListAccountsReq{}
	mi := &file_bank_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsReq) ProtoMessage() {}

func (x *ListAccountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsReq.ProtoReflect.Descriptor instead.
func (*ListAccountsReq) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{10}
}

func (x *ListAccountsReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAccountsReq) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAccountsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRsp) Reset() {
	*x = ListAccountsRsp{}
	mi := &file_bank_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRsp) ProtoMessage() {}

func (x *ListAccountsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRsp.ProtoReflect.Descriptor instead.
func (*ListAccountsRsp) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccountsRsp) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type TransferReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	mi := &file_bank_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{12}
}

func (x *TransferReq) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *TransferReq) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *TransferReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransferRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccount   *Account               `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     *Account               `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRsp) Reset() {
	*x = TransferRsp{}
	mi := &file_bank_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRsp) ProtoMessage() {}

func (x *TransferRsp) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRsp.ProtoReflect.Descriptor instead.
func (*TransferRsp) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{13}
}

func (x *TransferRsp) GetFromAccount() *Account {
	if x != nil {
		return x.FromAccount
	}
	return nil
}

func (x *TransferRsp) GetToAccount() *Account {
	if x != nil {
		return x.ToAccount
	}
	return nil
}

var File_bank_proto protoreflect.FileDescriptor

const file_bank_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bank.proto\x12\tbank.v1_1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xba\x01\n" +
	"\rCreateUserReq\x12?\n" +
	"\tuser_name\x18\x01 \x01(\tB\"\xfaB\x1fr\x1d2\x1b^[A-Za-z0-9][A-Za-z0-9_-]*$R\buserName\x12$\n" +
	"\tfull_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bfullName\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\bpassword\x12\x1d\n" +
	"\x05email\x18\x04 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\"C\n" +
	"\rCreateUserRsp\x122\n" +
	"\fcreated_user\x18\x01 \x01(\v2\x0f.bank.v1_1.UserR\vcreatedUser\"\xdb\x01\n" +
	"\x04User\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12J\n" +
	"\x13password_changed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x11passwordChangedAt\x127\n" +
	"\tcreate_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\"p\n" +
	"\bLoginReq\x12?\n" +
	"\tuser_name\x18\x01 \x01(\tB\"\xfaB\x1fr\x1d2\x1b^[A-Za-z0-9][A-Za-z0-9_-]*$R\buserName\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\bpassword\"[\n" +
	"\bLoginRsp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12,\n" +
	"\tuser_info\x18\x02 \x01(\v2\x0f.bank.v1_1.UserR\buserInfo\"M\n" +
	"\x10CreateAccountReq\x12\x1d\n" +
	"\x05owner\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05owner\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"O\n" +
	"\x10CreateAccountRsp\x12;\n" +
	"\x0fcreated_account\x18\x01 \x01(\v2\x12.bank.v1_1.AccountR\x0ecreatedAccount\"\x9e\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x127\n" +
	"\tcreate_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\"(\n" +
	"\rGetAccountReq\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"=\n" +
	"\rGetAccountRsp\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.bank.v1_1.AccountR\aaccount\"J\n" +
	"\x0fListAccountsReq\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\rB\t\xfaB\x06*\x04\x18\n" +
	"(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"A\n" +
	"\x0fListAccountsRsp\x12.\n" +
	"\baccounts\x18\x01 \x03(\v2\x12.bank.v1_1.AccountR\baccounts\"\xa8\x01\n" +
	"\vTransferReq\x12/\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\rfromAccountId\x12+\n" +
	"\rto_account_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\vtoAccountId\x12\x1f\n" +
	"\x06amount\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"w\n" +
	"\vTransferRsp\x125\n" +
	"\ffrom_account\x18\x01 \x01(\v2\x12.bank.v1_1.AccountR\vfromAccount\x121\n" +
	"\n" +
	"to_account\x18\x02 \x01(\v2\x12.bank.v1_1.AccountR\ttoAccount2\x8c\x03\n" +
	"\x04Bank\x12@\n" +
	"\n" +
	"CreateUser\x12\x18.bank.v1_1.CreateUserReq\x1a\x18.bank.v1_1.CreateUserRsp\x121\n" +
	"\x05Login\x12\x13.bank.v1_1.LoginReq\x1a\x13.bank.v1_1.LoginRsp\x12I\n" +
	"\rCreateAccount\x12\x1b.bank.v1_1.CreateAccountReq\x1a\x1b.bank.v1_1.CreateAccountRsp\x12@\n" +
	"\n" +
	"GetAccount\x12\x18.bank.v1_1.GetAccountReq\x1a\x18.bank.v1_1.GetAccountRsp\x12F\n" +
	"\fListAccounts\x12\x1a.bank.v1_1.ListAccountsReq\x1a\x1a.bank.v1_1.ListAccountsRsp\x12:\n" +
	"\bTransfer\x12\x16.bank.v1_1.TransferReq\x1a\x16.bank.v1_1.TransferRspB3Z1github.com/lmkzero/simple-bank/api/bank/v1_1;v1_1b\x06proto3"

var (
	file_bank_proto_rawDescOnce sync.Once
	file_bank_proto_rawDescData []byte
)

func file_bank_proto_rawDescGZIP() []byte {
	file_bank_proto_rawDescOnce.Do(func() {
		file_bank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_proto_rawDesc), len(file_bank_proto_rawDesc)))
	})
	return file_bank_proto_rawDescData
}

var file_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_bank_proto_goTypes = []any{
	(*CreateUserReq)(nil),         // 0: bank.v1_1.CreateUserReq
	(*CreateUserRsp)(nil),         // 1: bank.v1_1.CreateUserRsp
	(*User)(nil),                  // 2: bank.v1_1.User
	(*LoginReq)(nil),              // 3: bank.v1_1.LoginReq
	(*LoginRsp)(nil),              // 4: bank.v1_1.LoginRsp
	(*CreateAccountReq)(nil),      // 5: bank.v1_1.CreateAccountReq
	(*CreateAccountRsp)(nil),      // 6: bank.v1_1.CreateAccountRsp
	(*Account)(nil),               // 7: bank.v1_1.Account
	(*GetAccountReq)(nil),         // 8: bank.v1_1.GetAccountReq
	(*GetAccountRsp)(nil),         // 9: bank.v1_1.GetAccountRsp
	(*ListAccountsReq)(nil),       // 10: bank.v1_1.ListAccountsReq
	(*ListAccountsRsp)(nil),       // 11: bank.v1_1.ListAccountsRsp
	(*TransferReq)(nil),           // 12: bank.v1_1.TransferReq
	(*TransferRsp)(nil),           // 13: bank.v1_1.TransferRsp
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_bank_proto_depIdxs = []int32{
	2,  // 0: bank.v1_1.CreateUserRsp.created_user:type_name -> bank.v1_1.User
	14, // 1: bank.v1_1.User.password_changed_at:type_name -> google.protobuf.Timestamp
	14, // 2: bank.v1_1.User.create_at:type_name -> google.protobuf.Timestamp
	2,  // 3: bank.v1_1.LoginRsp.user_info:type_name -> bank.v1_1.User
	7,  // 4: bank.v1_1.CreateAccountRsp.created_account:type_name -> bank.v1_1.Account
	14, // 5: bank.v1_1.Account.create_at:type_name -> google.protobuf.Timestamp
	7,  // 6: bank.v1_1.GetAccountRsp.account:type_name -> bank.v1_1.Account
	7,  // 7: bank.v1_1.ListAccountsRsp.accounts:type_name -> bank.v1_1.Account
	7,  // 8: bank.v1_1.TransferRsp.from_account:type_name -> bank.v1_1.Account
	7,  // 9: bank.v1_1.TransferRsp.to_account:type_name -> bank.v1_1.Account
	0,  // 10: bank.v1_1.Bank.CreateUser:input_type -> bank.v1_1.CreateUserReq
	3,  // 11: bank.v1_1.Bank.Login:input_type -> bank.v1_1.LoginReq
	5,  // 12: bank.v1_1.Bank.CreateAccount:input_type -> bank.v1_1.CreateAccountReq
	8,  // 13: bank.v1_1.Bank.GetAccount:input_type -> bank.v1_1.GetAccountReq
	10, // 14: bank.v1_1.Bank.ListAccounts:input_type -> bank.v1_1.ListAccountsReq
	12, // 15: bank.v1_1.Bank.Transfer:input_type -> bank.v1_1.TransferReq
	1,  // 16: bank.v1_1.Bank.CreateUser:output_type -> bank.v1_1.CreateUserRsp
	4,  // 17: bank.v1_1.Bank.Login:output_type -> bank.v1_1.LoginRsp
	6,  // 18: bank.v1_1.Bank.CreateAccount:output_type -> bank.v1_1.CreateAccountRsp
	9,  // 19: bank.v1_1.Bank.GetAccount:output_type -> bank.v1_1.GetAccountRsp
	11, // 20: bank.v1_1.Bank.ListAccounts:output_type -> bank.v1_1.ListAccountsRsp
	13, // 21: bank.v1_1.Bank.Transfer:output_type -> bank.v1_1.TransferRsp
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_bank_proto_init() }
func file_bank_proto_init() {
	if File_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_proto_rawDesc), len(file_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_proto_goTypes,
		DependencyIndexes: file_bank_proto_depIdxs,
		MessageInfos:      file_bank_proto_msgTypes,
	}.Build()
	File_bank_proto = out.File
	file_bank_proto_goTypes = nil
	file_bank_proto_depIdxs = nil
}
